### ISSUE TITLE
Intro to neural networks

### ISSUE THREAD

**Issue by sl2902** [udacity/dlnd-issue-reports#120]

**Comment by sl2902** [comment]
In lesson 4 Neural Network, when Luis is answering the 2nd question as to whether the Test/Grade lies above or below the orange the line, the orientation of the data points in the visual is different from that used to answer the 1st question. Shouldn't they be the same?

**Comment by clapollo** [comment]
No, this is how you divide a region up with multiple lines. So each line cuts through the data at a different angle, separating it into multiple regions. The ideas of "above" and "below" become a bit trickier, so I guess this could use some notes about how those sides were chosen.

**Comment by lcrucks** [comment]
So, as a note here: You can tell if any given point is above or below a given line, regardless of that line's angle of descent / ascent, by comparing the y value of the point with the y value of the line at the same x value of the point.  (It does become impossible to specify a 'below' or 'above' on a perfectly vertical line, since a vertical line will have all possible y values, and will likely not even ever have the same x value as the point at any time.)
