### ISSUE TITLE
Can't access content (that's part of another ND) linked from 'Intro to TensorFlow'

### ISSUE THREAD

**Issue by kulshekhar** [udacity/dlnd-issue-reports#139]
The `Intro to TensorFlow` > `Hello, Tensor World!` > `Session` section links to https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/7751ab37-b759-49df-858b-f5498d4b006a/concepts/75d0ae66-a676-424f-8fd4-3f0c23154f48 which, when followed, results in the following message:

**You are not allowed to access this Nanodegree Program. Is your subscription paused, or past due?**

**Comment by clapollo** [comment]
Link has been removed.

**Comment by kulshekhar** [comment]
@clapollo  I'm sorry but that doesn't seem like the best way to resolve & close this issue.

The link was originally there to (most likely) help readers learn more about computational graphs. If that content is already present in the current course, the link should be pointed there. If the course doesn't have that content, it should be added.

**Comment by clapollo** [comment]
My guess is that the course developers determined that  information wasn't necessary for this lesson, so it was removed. I only noticed it because I was checking the lesson to fix this issue, but there was no link there to fix. If they end up deciding the content needs to be here, I'm sure they'll add it back in. Sorry!
