### ISSUE TITLE
Seq2seq hyperlinks

### ISSUE THREAD

**Issue by sashank06** [udacity/dlnd-issue-reports#262]
Seq2seq hyperlinks are not redirecting to the proper pages. tf.contrib.seq2seq.simple_decoder_fn_train  and tf.contrib.seq2seq.dynamic_rnn_decoder don’t work

**Comment by NeverDoubtTheWorm** [comment]
This seems to be because tensorflow dropped these functions with their 1.1 release. And the docs currently refer to the release version. Hard linking to the 1.0 revision of the doc will get you the page back but I feel that that's more of a temporary solution. 
For example: the link for simple_decoder_fn_train would be 
https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/seq2seq/simple_decoder_fn_train

**Comment by oritavital** [comment]
tf.contrib.seq2seq.dynamic_rnn_decoder  fixed in the classroom.

@sashank06 - can you say where did you see that link:
tf.contrib.seq2seq.simple_decoder_fn_train

**Comment by sashank06** [comment]
@oritavital  It's in the Decoder during training section.
The correct hyperlink should be https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/seq2seq/simple_decoder_fn_train

**Comment by oritavital** [comment]
I meant where in the classroom? can you link to the specific concept? I couldn't find it
