### ISSUE TITLE
Can't access Project 2 HTML page

### ISSUE THREAD

**Issue by troyjc** [udacity/dlnd-issue-reports#296]
When I go to Lesson 14 I only see one section in the left sidebar, i.e., only "1. Introduction to the Project"

My situation may be a nit unusual, because I have (a) a personal MacBook Pro laptop, (b) a work MabBook Pro laptop, and (c) a Ubuntu desktop with a Titan X GPU card.

I tend to use all three machines, depending on whether I'm traveling or I need the GPU.

On my personal laptop, I see the section "2. Project Image Classification." However, on my work laptop I don't. I just have the first section (the introduction).

Given that I'm traveling all this week, I want to be able to submit the project. I can't do that if that page doesn't show up!

Thank you,
Troy

**Comment by clapollo** [comment]
Don't worry, this situation is not specific to you. Something happened (I don't know what) and all students lost access to that project. We're looking into it and will fix it ASAP. 

It also means other project  due dates are all wrong because they seem to have adjusted themselves because of the missing project.

In any event, do not worry if you cannot turn in your project this week. You can just turn it in when you get back. There is no penalty for missing the deadline.

We're really sorry for this inconvenience and once we figure out what happened, we'll do everything we can to make sure it doesn't happen again.

**Comment by troyjc** [comment]
Thank you for the update.

Troy

**Comment by mcleonard** [comment]
No longer using this project, so not an issue anymore.
