### ISSUE TITLE
tflearn sentiment analysis - low accuracy

### ISSUE THREAD

**Issue by alkadagar** [udacity/dlnd-issue-reports#320]
After following the solutions notebook step-by-step, the accuracy is around 50% only.

**Comment by ghost** [comment]
I also tried re-running the solution and had the same issue.  My accuracy was only around 50%

**Comment by ghost** [comment]
Someone posted a [solution](https://discussions.udacity.com/t/low-accuracy-in-tflearn-sentiment-analysis/263856/15?u=greencpp10) to fix the problem in the forum.  It appears the solution has a bug in code:
The code in **Train, Validation, Test sets** section should be as following:
```
trainX, trainY = word_vectors[train_split,:], to_categorical(Y.values[train_split,0], 2)
testX, testY = word_vectors[test_split,:], to_categorical(Y.values[test_split,0], 2)
```
instead of 
```
trainX, trainY = word_vectors[train_split,:], to_categorical(Y.values[train_split], 2)
testX, testY = word_vectors[test_split,:], to_categorical(Y.values[test_split], 2)
```
 changing `Y.values[train_split]` to `Y.values[train_split,0]`  and changing   `Y.values[test_split]` to  `Y.values[test_split,0]` converts to a one dimensional array which is what the `to_categorical` method is looking for.

**Comment by lcrucks** [comment]
https://udacity.atlassian.net/browse/DLND-1150
