### ISSUE TITLE
Project tv script only work with TF 1.1

### ISSUE THREAD

**Issue by letyrodridc** [udacity/dlnd-issue-reports#404]
**Add a TF version 1.1 check into the TV Script notebook project  https://github.com/udacity/deep-learning/blob/master/tv-script-generation/dlnd_tv_script_generation.ipynb.**
Students get strange errors using a TF version different than 1.1. They need to:
```
pip uninstall tensorflow
pip install tensorflow=1.1
```
as workaround.
They expend a lot of time trying to understand what they did wrong in the notebook.
Some notebooks include a TF version check, this could be added to this notebook. 

For example: https://github.com/udacity/deep-learning/blob/master/face_generation/dlnd_face_generation.ipynb

![version](https://user-images.githubusercontent.com/9123307/33837843-7dc91952-de6c-11e7-9546-4265ae82d8da.png)

Code:
```
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
from distutils.version import LooseVersion
import warnings
import tensorflow as tf

# Check TensorFlow Version
assert LooseVersion(tf.__version__) >= LooseVersion('1.0'), 'Please use TensorFlow version 1.0 or newer.  You are using {}'.format(tf.__version__)
print('TensorFlow Version: {}'.format(tf.__version__))

# Check for a GPU
if not tf.test.gpu_device_name():
    warnings.warn('No GPU found. Please use a GPU to train your neural network.')
else:
    print('Default GPU Device: {}'.format(tf.test.gpu_device_name()))
```

**Comment by lcrucks** [comment]
Good advice for a workaround; this is a known issue that I would like to fix before Christmas (the notebook not working for up-to-date TF)

**Comment by hjwk** [comment]
While waiting for an updated version using an up to date TF, at least modify the assertion to verfiy that tf is not greater than 1.1 which is the reportedly the last compatible with the project.

**Comment by markr9805** [comment]
This issue is a real pain point. I had spent a good deal of time getting a CUDA 9.0 configuration running so that I could use Tensorflow 1.5 / 1.6. When I get to this project, I find I need to downgrade my system to CUDA 8.0 in order to be compatible with Tensorflow 1.0 or 1.1.

There should be documentation at the beginning of the entire class stating that the requirement is to use Tensorflow no greater than 1.1 in order to take the class, or to fix the unit tests so that they do not fail on later Tensorflow versions. I'm not sure which way this problem is being worked, but adding a note to the class requirements at the beginning of the course is a good (and quick) workaround until the code can be fixed.
