### ISSUE TITLE
Error in the multiplication

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/dlnd-issue-reports#412]
Refer to this Discussion Forum post https://discussions.udacity.com/t/multiplication-error-in-matrix-video/492881

**Comment by lcrucks** [comment]
https://classroom.udacity.com/nanodegrees/nd101/parts/bc6e1adc-6149-4d81-a96e-68baf31c1810/modules/1a8f9ad8-4c56-451b-b1d8-0600424a8a67/lessons/bd6228e5-42e6-43e4-beea-218fc5ad6ac2/concepts/4b63f617-19bd-4dd0-a2b3-fdd6e2df241b

Second matrix should have 6 8 10 on the bottom instead of 6 7 10 on the bottom

Internal Ticket: https://udacity.atlassian.net/browse/DLND-1259
