### ISSUE TITLE
In lecture 21 of Intro to TensorFlow

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/dlnd-issue-reports#431]
I agree with the student in this discussion forum post;

https://discussions.udacity.com/t/sigma-interpretation/533530

**Comment by lcrucks** [comment]
Student's post (Q2 was the one brought up):

In lecture 21 of Intro to TensorFlow, the instructor says the following “The sigma value determines the order of magnitude of your outputs at the initial point of your optimization. Because of the soft max on top of it, the order of magnitude also determines the peakiness of your initial probability distribution. A large sigma means that your distribution will have large peaks, so it’s going to be very opinionated. A small sigma means that your distribution is very uncertain about things.”

First question - Can you further explain how the sigma value determines the order of magnitude of the outputs? I believe the sigma just determines the range of weight values and likelihood of values within the range. For a normal distribution, its 68% likely that the weights would fall within 1 standard deviation(sigma) and thus most of the weight values will fall within 1 and -1. When referencing order of magnitiude of outputs, its this just saying a larger sigma could lead to weight values falling within a larger range,(-2,2) or (-3,3) and in turn, when multiplied by inputs, the outputs are larger?

Second Question - I thought a larger sigma (covers a wider range) would have small peaks and be less opinionated(because it covers a wider range) and thus less certain. In turn, a smaller sigma(covers less range) would be more opinionated because it is more peaky? I’m obviously wrong, but these were my initial thoughts.

Thanks in advance!

**Comment by lcrucks** [comment]
You're right, btw (I believe this part of the course has been depreciated), but a small sigma is more opinionated and has higher peaks than a large sigma.
