### ISSUE TITLE
Tensorflow 1.6 not usable

### ISSUE THREAD

**Issue by PhilippRamjoue** [udacity/dlnd-issue-reports#519]
I take part at the Deep Learning Nanodegree. In Lesson 2 "Applying Deep Learning" you have to try the Style Transfer algorithm. For that you have to install:

conda create -n style-transfer python=2.7.9
source activate style-transfer
pip install tensorflow
conda install scipy pillow

the installed Tensorflow version is 1.6 that isn't working in that case. I had to downgrade to 1.5. Maybe you can edit this to the instructions.

THX

**Comment by Abdulaziz-Alhefdhi** [comment]
neither Tensorflow 1.6 nor 1.5 worked for me. My OS is windows 10 on surface pro 4. I get this warning:
2018-03-13 20:13:20.137714: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2

the computer tries to run the program and everything goes slow because the memory and cpu are busy, and then the program gets interrupted and terminated

**Comment by Abdulaziz-Alhefdhi** [comment]
for me I just realized the reason Tensorflow was because the size of the image I chose was 4MB. when I tried another image (400KB) it worked, still slow though.
