### ISSUE TITLE
error: link of gradient descent

### ISSUE THREAD

**Issue by edmundex** [udacity/dlnd-issue-reports#527]
in lesson 1 13. Log-loss lecture,it said "We pick back up on log-loss error with the gradient descent concept, here." in the middle, but the link "here" doesn't work

it redirects me to a message "You are not allowed to access this Nanodegree Program. Is your subscription paused, or past due?"

**Comment by lcrucks** [comment]
(Internal note: student is speaking of this location in the classroom: https://classroom.udacity.com/nanodegrees/nd101/parts/73a7fe8e-4354-4362-939d-a8bf2bae870d/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/5e1f6c71-6c75-4bb2-98a9-ee40c0eb3472)

Hi,

I apologize for this; there isn't an easy way to fix it.  This particular node is shared with the driverless car program, and there isn't a way for the link to be routed only to the correct location for a given Nanodegree.  Because of this, I've added an alternative link that should work for DLND.
