### ISSUE TITLE
Lessons 5,6,7 are not showing completed

### ISSUE THREAD

**Issue by PythonWillRule** [udacity/dlnd-issue-reports#88]
What can I do?

**Comment by PythonWillRule** [comment]
Never mind I figure it out

**Comment by jzemel** [comment]
How did you solve it? Lessons 1-7 are all showing 0% complete for me.

**Comment by oritavital** [comment]
When you go through the different concepts in the lesson, they should be marked as completed (green check mark). When you complete all of them the lesson will be marked as complete.
If you still have issues with that, please email our support team (deeplearning-support@udacity.com). 
Thanks!

**Comment by jzemel** [comment]
In my case, I did observe the check mark and the complete lessons all the way through project 1. When I returned to the classroom, the progress appeared to be lost (0% complete lessons). I emailed support@udacity actually and got the automatic response, but no one ever followed up. Any other suggestions? (it's not preventing me from taking the class but I have to keep all my code quizzes in text files to refer to them later because they could just be lost in the classroom)
